--execute as c##svvcore
create table main_table
(
  id INTEGER generated by default as identity,
  name nvarchar2(100)
);

create table copy_table
(
  id INTEGER generated by default as identity,
  name nvarchar2(100)
);

create table journal_table
(
  datetime date,
  info nvarchar2(10),
  timeinfo timestamp
);

drop table main_table;
drop table copy_table;
drop table journal_table;
commit;

declare
  i number := 1;
  temp varchar(100);
begin
  loop
    temp := CONCAT('Value ', to_char(i));
    insert into main_table (name) values (temp);
    i := i + 1;
  exit when i > 100;
  end loop;
end;

select * from main_table where rownum <= 5;
delete main_table where rownum <= 5;
commit;

insert into copy_table select * from main_table where rownum <= 5 ;
select * from copy_table;
rollback;









